# Generated by Django 5.0.3 on 2024-03-13 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0082_totalguest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='idrestaurant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pincode',
        ),
    ]
